services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\Signature\Serializer\JWSSerializerManagerFactory:
        public: true
    Jose\Component\Signature\Serializer\CompactSerializer: ~
    Jose\Component\Signature\Serializer\JSONFlattenedSerializer: ~
    Jose\Component\Signature\Serializer\JSONGeneralSerializer: ~
