services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Jose\Component\Encryption\NestedTokenLoaderFactory: ~
    Jose\Component\Encryption\NestedTokenBuilderFactory: ~
