splits:
  - prefix: "src/Deprecated/Checker"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-checker.git"
  - prefix: "src/Deprecated/Console"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-console.git"
  - prefix: "src/Deprecated/Core"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-core.git"
  - prefix: "src/Deprecated/Ecc"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-util-ecc.git"
  - prefix: "src/Deprecated/Encryption"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption.git"
  - prefix: "src/Deprecated/KeyManagement"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-key-mgmt.git"
  - prefix: "src/Deprecated/NestedToken"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-nested-token.git"
  - prefix: "src/Deprecated/Signature"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-signature.git"
  - prefix: "src/JoseFramework"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-bundle.git"
  - prefix: "src/Component"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-library.git"
  - prefix: "src/EncryptionAlgorithm/ContentEncryption/AESCBC"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption-algorithm-aescbc.git"
  - prefix: "src/EncryptionAlgorithm/ContentEncryption/AESGCM"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption-algorithm-aesgcm.git"
  - prefix: "src/EncryptionAlgorithm/KeyEncryption/AESGCMKW"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption-algorithm-aesgcmkw.git"
  - prefix: "src/EncryptionAlgorithm/KeyEncryption/AESKW"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption-algorithm-aeskw.git"
  - prefix: "src/EncryptionAlgorithm/KeyEncryption/Direct"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption-algorithm-dir.git"
  - prefix: "src/EncryptionAlgorithm/KeyEncryption/ECDHES"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption-algorithm-ecdh-es.git"
  - prefix: "src/EncryptionAlgorithm/KeyEncryption/PBES2"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption-algorithm-pbes2.git"
  - prefix: "src/EncryptionAlgorithm/KeyEncryption/RSA"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption-algorithm-rsa.git"
  - prefix: "src/SignatureAlgorithm/ECDSA"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-signature-algorithm-ecdsa.git"
  - prefix: "src/SignatureAlgorithm/EdDSA"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-signature-algorithm-eddsa.git"
  - prefix: "src/SignatureAlgorithm/None"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-signature-algorithm-none.git"
  - prefix: "src/SignatureAlgorithm/HMAC"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-signature-algorithm-hmac.git"
  - prefix: "src/SignatureAlgorithm/RSA"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-signature-algorithm-rsa.git"
  - prefix: "src/SignatureAlgorithm/Experimental"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-signature-algorithm-experimental.git"
  - prefix: "src/EncryptionAlgorithm/Experimental"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-encryption-algorithm-experimental.git"
  - prefix: "src/Experimental"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-experimental.git"
  - prefix: "packs/encryption"
    target: "https://${GH_TOKEN}@github.com/web-token/encryption-pack.git"
  - prefix: "packs/signature"
    target: "https://${GH_TOKEN}@github.com/web-token/signature-pack.git"

origins:
  - ^\d+\.\d+\.x$
  - ^\d+\.\d+\.\d+$
