splits:
  - prefix: "src/Bundle"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-bundle.git"
  - prefix: "src/Library"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-library.git"
  - prefix: "src/Experimental"
    target: "https://${GH_TOKEN}@github.com/web-token/jwt-experimental.git"

origins:
  - ^\d+\.\d+\.x$
  - ^\d+\.\d+\.\d+$
