before_commands:
    - "composer install --prefer-dist"

tools:
    external_code_coverage: false
    php_mess_detector: true
    php_code_sniffer: true
    php_analyzer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_sim: false
    php_cpd: true
    php_pdepend:
        excluded_dirs: ["vendor/*", "performance/*", "*Tests/*"]
filter:
    excluded_paths: ["vendor/*", "performance/*", "*Tests/*"]
build_failure_conditions:
    - 'elements.rating(<= D).new.exists'           # No new classes/methods with a rating of D or worse
    - 'issues.severity(>= MAJOR).new.exists'       # New issues of major or higher severity
    - 'project.metric("scrutinizer.quality", < 9)' # Code Quality Rating drops below 6
