dist: trusty
sudo: false
language: php

php:
    - 7.2
    - 7.3
    - nightly

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_script:
    - mkdir -p build/logs

before_install:
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: travis_retry composer install

script:
    - ./vendor/bin/phpunit --group=unit
    - ./vendor/bin/phpunit --group=functional

jobs:
    allow_failures:
        - php: nightly

    include:
        - stage: Metrics and quality
          env: COVERAGE
          before_script:
              - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
              - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
          script:
              - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
          after_script:
              - ./vendor/bin/coveralls --no-interaction

        - stage: Metrics and quality
          env: BENCHMARK
          script:
              - echo "Disabled"
              #- ./vendor/bin/phpbench run -l dots --report aggregate

        - stage: Metrics and quality
          env: CODE_STANDARD
          script:
              - echo "Disabled"
              #- ./vendor/bin/phpcs

        - stage: Metrics and quality
          env: MUTATION
          before_script:
              - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
              - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
          script:
              - ./vendor/bin/infection --test-framework-options="--group=unit" -s --threads=$(nproc) --min-msi=95 --min-covered-msi=95

        - stage: Metrics and quality
          env: STATIC_ANALYSIS
          script:
              - ./vendor/bin/phpstan analyse
