<?php

declare(strict_types=1);

namespace Jose\Tests\EncryptionAlgorithm\KeyEncryption\ECDHES;

use Jose\Component\Core\JWK;
use Jose\Component\Core\Util\ECKey;
use Jose\Component\Encryption\Algorithm\KeyEncryption\ECDHES;
use Jose\Component\Encryption\Algorithm\KeyEncryption\ECDHESA128KW;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

/**
 * @internal
 */
final class BrainpoolKeyAgreementTest extends TestCase
{
    #[Test]
    #[DataProvider('curves')]
    public function theSenderAndTheRecipientAgreeOnTheSameKey(string $curve): void
    {
        $recipientKey = ECKey::createECKey($curve);
        $algorithm = new ECDHES();
        $header = [
            'enc' => 'A128GCM',
            'apu' => 'QWxpY2U',
            'apv' => 'Qm9i',
        ];

        $additionalHeaderValues = [];
        $senderAgreementKey = $algorithm->getAgreementKey(
            128,
            'A128GCM',
            $recipientKey->toPublic(),
            null,
            $header,
            $additionalHeaderValues
        );

        static::assertArrayHasKey('epk', $additionalHeaderValues);
        static::assertSame($curve, $additionalHeaderValues['epk']['crv']);
        static::assertArrayHasKey('y', $additionalHeaderValues['epk']);

        $recipientAgreementKey = $algorithm->getAgreementKey(
            128,
            'A128GCM',
            $recipientKey,
            null,
            $header + $additionalHeaderValues
        );

        static::assertSame($senderAgreementKey, $recipientAgreementKey);
    }

    #[Test]
    #[DataProvider('curves')]
    public function theContentEncryptionKeyIsWrappedAndUnwrapped(string $curve): void
    {
        $recipientKey = ECKey::createECKey($curve);
        $algorithm = new ECDHESA128KW();
        $header = [
            'alg' => 'ECDH-ES+A128KW',
            'enc' => 'A128GCM',
        ];
        $cek = random_bytes(16);

        $additionalHeaderValues = [];
        $encryptedCek = $algorithm->wrapAgreementKey(
            $recipientKey->toPublic(),
            null,
            $cek,
            128,
            $header,
            $additionalHeaderValues
        );

        static::assertSame(
            $cek,
            $algorithm->unwrapAgreementKey($recipientKey, null, $encryptedCek, 128, $header + $additionalHeaderValues)
        );
    }

    /**
     * The ephemeral key generated by the sender must be a fresh key on the recipient curve.
     */
    #[Test]
    #[DataProvider('curves')]
    public function theEphemeralKeyIsGeneratedOnTheRecipientCurve(string $curve): void
    {
        $recipientKey = ECKey::createECKey($curve);
        $algorithm = new ECDHES();

        $additionalHeaderValues = [];
        $algorithm->getAgreementKey(128, 'A128GCM', $recipientKey->toPublic(), null, [], $additionalHeaderValues);

        $ephemeralKey = new JWK($additionalHeaderValues['epk']);

        static::assertSame('EC', $ephemeralKey->get('kty'));
        static::assertSame($curve, $ephemeralKey->get('crv'));
        static::assertFalse($ephemeralKey->has('d'));
        static::assertNotSame($recipientKey->get('x'), $ephemeralKey->get('x'));
    }

    /**
     * @return iterable<string, array{string}>
     */
    public static function curves(): iterable
    {
        yield 'BP-256' => ['BP-256'];
        yield 'BP-384' => ['BP-384'];
        yield 'BP-512' => ['BP-512'];
    }
}
