name: "Infection"

on:
  push:
    branches:
      - "*.x"

jobs:
  mutation_testing:
    name: "0️⃣ Mutation Testing"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.3"
          extensions: "json, mbstring, openssl, sqlite3, curl, uuid"
          tools: castor

      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          composer-options: "--optimize-autoloader"

      - name: "Execute Infection"
        run: "castor infect"
