name: bot-auto-merge

on:
  check_suite:
    types:
      - completed

jobs:
  merge-me:
    name: Auto-merge passing bot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge passing dependabot PRs
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          # For clarity only. dependabot is default.
          GITHUB_LOGIN: dependabot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLED_FOR_MANUAL_CHANGES: "true"
